### ISSUE TITLE
onKeyUp instead of onChange in Search.js?

### ISSUE THREAD

**Issue by zzrez** [samie820/hooks-movie-app#1]
A great tutorial at the right time. I tried onKeyUp in the section
`<input
        value={searchValue}
        onChange={handleSearchInputChanges}
        type="text"
/>` to see if the results could be dynamically modified as you type and to avoid use of the Search button, but the input field then does not accept input. Any way to get this to work? Thanks

**Comment by samie820** [comment]
Hi @zzrez, unfortunately, I've been unavailable for a while, is this still an issue for you?

**Comment by zzrez** [comment]
Hi @samie820 have moved on too much! Thanks anyway.
